# docker-compose.test.yml
services:
  tracktags:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_REALTIME_URL=${SUPABASE_REALTIME_URL}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - BIND_ADDRESS=0.0.0.0
      - TRACKTAGS_PORT=8080
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    networks:
      - test-network

  webhook:
    image: python:3.9-slim
    command: python -m http.server 9090
    ports:
      - "9090:9090"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
