name = "tracktags"
version = "1.0.0"

[package]
name = "tracktags"
version = "1.0.0"
gleam_version = ">= 1.0.0"

[dependencies]
gleam_stdlib = ">= 0.60.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
mint = ">= 1.7.1 and < 2.0.0"
httpoison = ">= 2.2.3 and < 3.0.0"
genserver = "0.1.1" 
jason = ">= 1.4.4 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[build-tools]
erlang = ["mix"]

