name = "tracktags"
version = "1.0.0"

[package]
name = "tracktags"
version = "1.0.0"
gleam_version = ">= 1.0.0"

[dependencies]
gleam_stdlib = ">= 0.60.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
jason = ">= 1.4.4 and < 2.0.0"
glixir = ">= 1.0.0 and < 2.0.0"
logging = ">= 1.3.0 and < 2.0.0"
mist = ">= 5.0.1 and < 6.0.0"
wisp = ">= 1.8.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_crypto = ">= 1.5.1 and < 2.0.0"
birl = ">= 1.8.0 and < 2.0.0"
gun = ">= 2.2.0 and < 3.0.0"
cachex = ">= 4.1.1 and < 5.0.0"
uuid = ">= 1.1.8 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"


